### ISSUE TITLE
[FEATURE REQUEST] Open correct Vue version docs

### ISSUE THREAD

**Issue by NukeJS** [nuxtlabs/vue-telescope-extensions#10]
It would be nice that when u click on the Vue.js version, that it opens; https://v1.vuejs.org when using Vue 1, https://vuejs.org when using Vue 2, and https://v3.vuejs.org when using Vue 3.

**Comment by atinux** [comment]
Nice idea @CodingWithNuke 

I think this should be quite easy to make by updating this line with a computed property: https://github.com/nuxtlabs/vue-telescope-extensions/blob/master/src/popup/App.vue#L56

Do you want to take make a PR for it? 😊

**Comment by NukeJS** [comment]
> Nice idea @CodingWithNuke
> 
> I think this should be quite easy to make by updating this line with a computed property: https://github.com/nuxtlabs/vue-telescope-extensions/blob/master/src/popup/App.vue#L56
> 
> Do you want to take make a PR for it? 😊

Sure, I'm on it!

**Comment by NukeJS** [comment]
PR @ https://github.com/nuxtlabs/vue-telescope-extensions/pull/11

**Comment by NukeJS** [comment]
New PR @ #12 since vue 3 is now the default
