### ISSUE TITLE
[FEATURE REQUEST] Adaptive icon in relation to the framework

### ISSUE THREAD

**Issue by cosimochellini** [nuxtlabs/vue-telescope-extensions#3]
It would be nice if, like the official vue extension, vue-telemetry also changed its icon in relation to what framework the page is using (vue / nuxt / gridsome / vue press) 😇😇😇

**Comment by atinux** [comment]
I do like the idea, but next to the Vue Devtools it might look quite similar 🤔

**Comment by cosimochellini** [comment]
In fact, IMHO since vue-telemetry offers more info than vue-devtool, I immediately hid the vue-devtool leaving only 
vue-telemetry in the omnibox of chrome/brave/edge/firefox , leaving vue-devtool "only" the task of debugging the apps

**Comment by atinux** [comment]
I see, this makes perfect sense, I actually did the same.

Cc @benjamincanac @bdrtsky @pi0  what do you think of this feature?

**Comment by pi0** [comment]
Nice idea indeed! We should be only careful about chrome dark theme with icons :D

**Comment by ghost** [comment]
Make it optional, please

**Comment by atinux** [comment]
Wappalyzer has an option for it:

![Screenshot 2020-09-30 at 11 58 14](https://user-images.githubusercontent.com/904724/94671523-495d1b80-0314-11eb-9952-1d23c788b34b.png)

**Comment by atinux** [comment]
A PR is more than welcome to support this :heart:

**Comment by undead-voron** [comment]
@Atinux I think this issue is resolved and can be closed
