### ISSUE TITLE
Chrome Linux https://web.whatsapp.com/ Crash

### ISSUE THREAD

**Issue by jerosoler** [nuxtlabs/vue-telescope-extensions#4]
By having the extension activated by default. The page does not load.

Vue telemtry extension: 1.3.0
Chrome: Versión 85.0.4183.102 (Build oficial) (64 bits)
Linux: KDE neon User Edition 5.19 - 18.04

I have had to configure the extension. When you click activate.

**Comment by bdrtsky** [comment]
Hello, @jerosoler 

Would love to check out this issue. Do I need to login into whatsapp account to reproduce this? Since it seems that I can open the page.

**Comment by jerosoler** [comment]
Hello @bdrtsky 

Registered and unregistered.

Attached capture of how it looks:

![image](https://user-images.githubusercontent.com/30957047/93132868-a337d180-f6d6-11ea-85f0-03d310047547.png)

Only activated vue telemetry in private browsing.

**Comment by bdrtsky** [comment]
<img width="943" alt="Screenshot 2020-09-15 at 16 05 38" src="https://user-images.githubusercontent.com/45076741/93214151-7a165000-f76d-11ea-8aee-4ed06846040a.png">

Can't reproduce it. Webpage is opening without errors for me...

**Comment by jerosoler** [comment]
Linux system?

**Comment by bdrtsky** [comment]
No, MacOS. But just checked on Ubuntu, it's also works.

**Comment by bdrtsky** [comment]
@jerosoler hello 👋 can you please check if this issue is still present with latest extension version?

**Comment by jerosoler** [comment]
Hello @bdrtsky 

This works!!! 🎉🎉

Thanks! 🤩💚
