### ISSUE TITLE
Affects local server

### ISSUE THREAD

**Issue by ghost** [nuxtlabs/vue-telescope-extensions#6]
Hi.
I encountered a conflict between the extension and my local server for PHP (it runs on `http://127.0.0.1/`)

![2020-09-25_112349](https://user-images.githubusercontent.com/11320080/94244482-9c545e80-ff21-11ea-8d63-6da691dfefdb.png)

So basically, I cannot log in there.
When the extension is disabled or in incognito - it works.
Win 10 / Chrome 85

**Comment by bdrtsky** [comment]
Hello. This should be resolved with latest version. Can you please check which one you use?

**Comment by ghost** [comment]
1.4.0

**Comment by ghost** [comment]
Also, tried extension with Edge - the same issue.

**Comment by atinux** [comment]
We just released [v1.4.1](https://github.com/nuxt-company/vue-telemetry-extensions/releases/tag/v1.4.1)

it might take a bit of time to update on Chrome store.

Do you mind trying the [manual installation](https://github.com/nuxt-company/vue-telemetry-extensions/blob/master/README.md#manual-installation) and confirming that it solves the issue @web2033 ?

**Comment by ghost** [comment]
Download the extension (.zip) - link doesn't work. It returns XML:
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>249444979/87be6a00-1232-11eb-80fa-d71bc1fa89b3</Key>
<RequestId>FD71291768A76444</RequestId>
<HostId>ryMLX9XbevQ+g16GW+Wnfuz+0Hn5tEyYv5r1CkUE+HwjKzot6Ed2tUoyeKhE2M2uRwhRipfLbQ0=</HostId>
</Error>
```

**Comment by ghost** [comment]
Got an update via Chrome Web Store to 1.4.1
Don't see that error anymore.

**Comment by atinux** [comment]
The download link for manual installation is fixed, thanks @web2033 

Glad to know this error is fixed, great work @bdrtsky !
